import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import gradientes from "../data/gradientes.json";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <nav className="bg-gradient-to-r from-blue-500 to-purple-600 p-4">
                    <ul className="flex space-x-4">
                        <li>
                            <Link
                                href="/"
                                className="text-white font-semibold hover:text-gray-200"
                            >
                                Início
                            </Link>
                        </li>
                        {Object.keys(gradientes).map((cor) => (
                            <li key={cor}>
                                <Link
                                    href={`/${cor.toLowerCase()}`}
                                    className="text-white font-semibold hover:text-gray-200"
                                >
                                    {cor}
                                </Link>
                            </li>
                        ))}
                        <li>
                            <Link
                                href="/galeria"
                                className="text-white font-semibold hover:text-gray-200"
                            >
                                Galeria
                            </Link>
                        </li>
                    </ul>
                </nav>
                <main>{children}</main>
            </body>
        </html>
    );
}
